=== MarkusH/pxchat/xml/pxchatlog.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- all elements -->
<!ELEMENT pxchatlog (participants, start, end, chat)>
<!ELEMENT participants (name)+>
<!ELEMENT name (#PCDATA)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end EMPTY>
<!ELEMENT chat (message)*>
<!ELEMENT message (#PCDATA)>

<!-- all attributes -->
<!ATTLIST name
	date	CDATA	#REQUIRED
	time	CDATA	#REQUIRED
>
<!ATTLIST start
	date	CDATA	#REQUIRED
	time	CDATA	#REQUIRED
>
<!ATTLIST end
	date	CDATA	#REQUIRED
	time	CDATA	#REQUIRED
>
<!ATTLIST img 
	src		CDATA	#REQUIRED
	alt		CDATA	#IMPLIED
>
<!ATTLIST message
	author	CDATA	#REQUIRED
	date	CDATA	#REQUIRED
	time	CDATA	#REQUIRED
	type	(text|system)	text
>

=== MarkusH/pxchat/xml/Example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pxchatlog SYSTEM "pxchatlog.dtd">
<?xml-stylesheet type="text/xsl" href="pxchatlog.xsl" ?>
<pxchatlog>
	<!-- all participants of the chat -->
	<participants>
		<name>John Doe</name>
		<name>Jane Doe</name>
		<name>Joe Everybody</name>
	</participants>
	<!-- duration -->
	<start date="01/04/2010" time="10:21:14" />
	<end date="01/04/2010" time="10:33:44" />
	<!-- the chat -->
	<chat>
		<message author="Jane Doe" date="01/04/2010" time="10:21:14">Hi!</message>
		<message author="Jane Doe" date="01/04/2010" time="10:21:23">What's up?</message>
		<message author="John Doe" date="01/04/2010" time="10:23:12">Not much</message>
		<message author="Jane Doe" date="01/04/2010" time="10:23:54">Check this out</message>
		<join user="Joe Everybody" date="01/04/2010" time="10:23:57" />
		<message author="Joe Everybody" date="01/04/2010" time="10:25:23">Sup</message>
		<message author="Jane Doe" date="01/04/2010" time="10:25:59">Bye!</message>
		<leave user="Jane Doe" date="01/04/2010" time="10:26:03" />
	</chat>
</pxchatlog>
