=== MarkusH/pxchat/data/xml/server.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT server (config, auth)>
<!ELEMENT config (port?, serverlist?)>
<!ELEMENT auth (user)*>
<!ELEMENT port EMPTY>
<!ELEMENT serverlist EMPTY>
<!ELEMENT user EMPTY>


<!ATTLIST port
	number	CDATA	#REQUIRED
>

<!ATTLIST serverlist
	url	CDATA	#REQUIRED
>

<!ATTLIST user
	name		CDATA	#REQUIRED
	password	CDATA	#REQUIRED
>

=== MarkusH/pxchat/data/config/server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE server SYSTEM "../xml/server.dtd">
<server>
	<config>
		<port number="12345" />
	</config>
	<auth>
		<user name="Kevin Articus" password="articus" />
		<user name="Sebastian Biewer" password="biewer" />
		<user name="Rene Engelmann" password="engelmann" />
		<user name="Robert Genz" password="genz" />
		<user name="Christian Jelitte" password="jelitte" />
		<user name="Clemens Wolf" password="wolf" />
		<user name="Florian Bausch" password="bausch" />
		<user name="Markus Döllinger" password="döllinger" />
		<user name="Markus Holtermann" password="holtermann" />
		<user name="Alexander Tenberge" password="tenberge" />
		<user name="Robert Waury" password="waury" />
	</auth>
</server>
